import Foundation

/// Every version, newest first, in his words — what was added, changed, fixed and
/// removed. His standing rule from the web apps: the version log and "How it works"
/// are updated on EVERY release. The UI test `testWhatsNewStartsWithThisVersion`
/// fails the build when the top entry is not the version being built, so a release
/// cannot slip out without its line here.
struct Release: Identifiable {
    let version: String
    let date: String
    let title: String
    var new: [String] = []
    var changed: [String] = []
    var fixed: [String] = []
    var removed: [String] = []
    var id: String { version }
}

enum Releases {
    static let all: [Release] = [
        Release(version: "0.56", date: "3 Oct 2026", title: "Your field test, part two",
                new: ["Pack to go home: search the list; Tick everything (and Clear the ticks); the heading counts what was used up \u{2014} \u{201C}1/2 \u{00B7} 1 used up\u{201D}. Each line takes a note (\u{201C}zip broken\u{201D}), and Open changes the thing and comes straight back.",
                      "Up to three photos of each packed bag. Tap one to see it large; Next steps through them. The way home shows them all.",
                      "Valid until says how far away the date is \u{2014} \u{201C}in 10 days\u{201D}, \u{201C}in 4 months\u{201D}, red once it has run out \u{2014} and +1 month, +6 months, +1 year, +5 years or +10 years sets it in one tap.",
                      "Choose from your things: every group folds with its arrow, or all at once with Fold all. A folded group still says how many things it holds and how many you ticked.",
                      "An \u{2715} in every search field empties it in one tap.",
                      "Settings: Your first real trip in 6 steps has its own door.",
                      "Save as Excel has a Category column, right after Thing."],
                changed: ["\u{201C}Shelf\u{201D} is now \u{201C}Activity area\u{201D}, the group a template lives in (GA, WET\u{2026}). Grab lists that are not on Home wait in Grab Lists.",
                          "\u{201C}Bought there\u{201D} is now \u{201C}Bought on site\u{201D}.",
                          "Picking trip dates: after the last day the calendar stays open and shows the range \u{2014} \u{201C}6 Oct \u{2013} 16 Oct \u{00B7} 10 nights\u{201D}. OK keeps it; Cancel puts the dates back.",
                          "Used up is taken back with Undo.",
                          "Your things: what you just added stays at the top, under Just added, until you leave the screen.",
                          "Renaming a bag takes each trip's scale reading and bag photos along; deleting one moves its photos to the bag its things go to."]),
        Release(version: "0.55", date: "3 Oct 2026", title: "Fixes from your field test",
                new: ["The Action button: a new Shortcuts action, Choose a grab list. One press opens all your grab lists as big tiles; tap the one for today.",
                      "On a trip, tap a bag: Goes in the cabin can be switched on right there \u{2014} also for a bag that was only a name on your lines. It then shows in Care \u{2192} Bags too."],
                changed: ["Quick says that Transport still counts: pick Plane and the cabin is checked.",
                          "A row on a template says what it is limited to: Only on: Summer.",
                          "What you tick in Reminders in the shop is ticked here as soon as you come back to the app."]),
        Release(version: "0.54", date: "3 Oct 2026", title: "iCloud sync, made visible",
                new: ["Settings \u{2192} iCloud sync: when this device last sent and received, what iCloud does not have yet, and \u{2014} if a send failed \u{2014} why, in plain words.",
                      "Sync now: this device checks in, and the other device's Settings shows it within a minute or so. A direct test of each direction.",
                      "Copy details for Claude: everything iCloud recorded on this device, to paste into the chat."]),
        Release(version: "0.53", date: "2 Oct 2026", title: "Pack to go home",
                new: ["Once a trip has begun (or something was bought there), the trip shows Pack to go home: what went and what you bought there, bag by bag, with ticks of its own. Used up takes a thing off. The photos of your packed bags sit at the top, to repack from. The ticks of the way out stay as they were, for the review."]),
        Release(version: "0.52", date: "2 Oct 2026", title: "A photo of the packed bag, and Bought there",
                new: ["Tap a bag on a trip's Bags: besides the luggage scale, Take a photo (or Choose a photo) of it packed. It stays with the trip; tap it to see it large \u{2014} the picture to repack from on the way home.",
                      "Bought something on the trip? Type it at the bottom of the list and press Bought there: it goes on, ticked, marked Bought there."]),
        Release(version: "0.51", date: "2 Oct 2026", title: "Shortcuts and the Action button",
                new: ["Two Shortcuts actions: Open a grab list (pick Swim, Bike, Run\u{2026}) and Open my next trip. Put one on the iPhone's Action button (Settings \u{2192} Action Button \u{2192} Shortcut), on the Home Screen, or ask Siri; they work in Shortcuts on the Mac too."]),
        Release(version: "0.50", date: "2 Oct 2026", title: "The luggage scale, and To buy in Reminders",
                new: ["On a trip's Bags, tap a bag and type what the luggage scale says. From then on that is the bag's weight \u{2014} the bag itself and everything never weighed included \u{2014} and the things' own sum stays under it. Over its max, the card turns red. Clear takes the reading away.",
                      "To do \u{2192} To buy: Send to Reminders puts the open lines into a Reminders list of their own, \u{201C}To buy \u{00B7} Packing\u{201D}, to take to the shop. Each line goes once; what you tick there is ticked here the next time you open the list."]),
        Release(version: "0.49", date: "2 Oct 2026", title: "Counting down, and reminders",
                new: ["Home counts down to your next trip, under the grab lists: the days in big figures, the trip, and the next packing step with when it is due. Tap it to open the trip.",
                      "Settings \u{2192} Remind me to pack: on this device, at 9 in the morning of the day each packing step is due (a week ahead, the day before, the morning\u{2026}), the trip and what is left to pack. Tap a reminder to open the trip. Off until you turn it on, so each device reminds you only if you want it to."]),
        Release(version: "0.48", date: "2 Oct 2026", title: "Check before you go",
                new: ["A trip shows Check before you go at the top when something needs you. On a plane trip: what in a cabin bag the airport stops \u{2014} not allowed on board in red, a liquid in orange (100 ml at most, in the clear bag). And what runs out before you are home; a passport or ID card six months ahead. Tap a line to open the thing and put it right.",
                      "A thing's page has On a plane (Liquid, Not allowed in the cabin) and Valid until (Add a date).",
                      "A bag's page has Goes in the cabin. A carry-on, hand luggage or cabin bag starts switched on."]),
        Release(version: "0.47", date: "2 Oct 2026", title: "Your first real trip",
                new: ["How it works starts with Your first real trip in 6 steps: backup, tidy your things, templates, the trip, packing, and the review afterwards."],
                changed: ["Laundry: you choose how many nights you pack for before a wash (3, 4, 5, 7, 10 or 14) — on Create new trip and in Trip settings. Every count, bag weight and the Excel file follow."]),
        Release(version: "0.46", date: "2 Oct 2026", title: "Icons, and eight grab lists",
                new: ["Every template has an icon — 50 drawn ones to choose from. Each starts with the one its name suggests (Swim, Bike, Run, Car, Plane…); tap the square on a template to pick another, or Letter for its first letter."],
                changed: ["Home holds eight grab lists, four in a row and slimmer. Free places fill from your shelf; when Home is full, a new list waits there as before.",
                          "Settings: Save a backup and Restore are further down, under Your choices, What's new and How it works.",
                          "Your choices: each part says what it is and where you use it.",
                          "A shared grab list takes a free place on Home, and says where it went."]),
        Release(version: "0.45", date: "1 Oct 2026", title: "A change to a thing reaches your trips",
                changed: ["Change a thing — its bag, weight, place or name — and the trips still ahead follow: coming-up and current trips, on every line you have not ticked and not changed on the trip itself. Ticked lines and finished trips keep what they were packed with. A bag chosen for one template still wins there."]),
        Release(version: "0.44", date: "30 Sep 2026", title: "The iPhone hears about changes",
                fixed: ["The iPhone app was built without permission to be told when iCloud has something new, so a trip made on the Mac showed up only after the app was opened again (your A.4). It now carries it, like the Mac app."]),
        Release(version: "0.43", date: "30 Sep 2026", title: "Actions is now To do",
                changed: ["The Actions tab is called To do — your choice. It still has both sides: To do and To buy."]),
        Release(version: "0.42", date: "28 Sep 2026", title: "Choosing things for a template",
                new: ["A template: Choose from your things. Every thing you own, grouped by Kind, From where, Into, When or A–Z, with a search. Tick as many as you like and Add them in one go; what is already on the template says so. A name you own nothing by becomes a new thing, straight onto the template.",
                      "A template's own things can be grouped the same ways: its sections, When, Into, From where, Kind or A–Z.",
                      "Trips: All your trips under Your year — trips, nights away, places and things packed, ever — and under it the map of where they went. Tap the map for the whole map."]),
        Release(version: "0.41", date: "28 Sep 2026", title: "Your test comments, part 2",
                new: ["How it works has a Words chapter: every word the app uses, said once — template, shelf, list, kit, the loop, review, refine and more."],
                changed: ["The loop strip carries the mark of the tab where each step is done: Plan on Home, Pack and Review on Trips, Refine on Templates. The picture says so too.",
                          "Refine on the Templates tab stands out: steps going up, in violet, with how many things wait.",
                          "Review: type what you missed, pick the template it goes onto, then Add it to that template — in that order, and the button says where."]),
        Release(version: "0.40", date: "28 Sep 2026", title: "Your test comments, part 1",
                new: ["Trip settings has the trip's place. Change it there and the weather starts again from the new place.",
                      "The date grid has Cancel: it closes and puts the dates back.",
                      "Taking a thing off a template with ✕ asks first, in the middle of the screen. The thing stays in Your things.",
                      "Save as Excel has two more columns: From where (where it is kept at home) and Into (the bag)."],
                changed: ["A pen, not a gear, opens a trip's settings.",
                          "Share is a real button, beside Save as Excel. Done, Save, Cancel and Share look like buttons everywhere.",
                          "The workouts have their own colours: Swim blue, Bike yellow, Run green, Strength orange, Breath work lavender, Mobility pink. Context sits set in under them, in grey.",
                          "Quick says what it means in green while it is on.",
                          "Grab lists: the count stays at the top while you scroll, and Not yet is a red card in the middle of the screen.",
                          "Headings on Care, Templates and Your choices are larger and in capitals. The heavy end is now Heaviest things.",
                          "In a thing's editor, each field sits right under its heading.",
                          "Trips: Now, Coming up and Done (was Been). Now is always there, with how many. The Reviewed arrow is much larger.",
                          "A new template asks: On which shelf should it live?"],
                fixed: ["A trip with a place but no forecast (already over, or too far ahead) now reaches the map. Before, only trips whose weather came back were on it."],
                removed: ["The round arrow at the end of the loop strip — it looked like a reload button."]),
        Release(version: "0.39", date: "28 Sep 2026", title: "A crash fixed",
                fixed: ["Changing a trip's dates, templates or laundry in Trip settings could close the app when the same thing was on the trip twice (from two templates, in two bags). Now each of those lines comes back once, with its own tick."]),
        Release(version: "0.38", date: "27 Sep 2026", title: "Share",
                new: ["Share a trip (at the end of its list), a template or a grab list (at their top): a link that opens in the web app and in this one, a QR code when it is short enough, and a trip also as a file.",
                      "Settings \u{2192} Open a shared link: paste a link or code and see what it holds. A trip arrives as a new trip, unticked. A template arrives as a new one, or in place of yours with the same name; things you already have keep your details. A grab list waits on your shelf."]),
        Release(version: "0.37", date: "27 Sep 2026", title: "Where you have been",
                new: ["Trips → the pin at the top: a map of your trips. One pin per place, with a number when you went more than once, a line through the trips oldest first, and a card per place with its trips. Tap a pin to find its card.",
                      "Trips that name a place but never looked up their weather can be found on the map in one press."],
                changed: ["Looking up a trip's weather now keeps the place's name for the map too."]),
        Release(version: "0.36", date: "27 Sep 2026", title: "Everything at once",
                new: ["Near the end of a trip: Tick everything (it says how many are still unticked), and Clear every tick, which asks first. Lines set aside stay out of both.",
                      "The weather card: Add all, when it asks for two or more things."],
                fixed: ["Weather gear you add from your own templates remembers where it came from, so the review counts it for that thing, and its weight reaches the bags."]),
        Release(version: "0.35", date: "27 Sep 2026", title: "Laundry and Excel",
                new: ["Laundry, on Create new trip and in Trip settings: wash and wear again, so per-night things count 4 nights at most. The line says \u{00D7}4 with a washtub.",
                      "Save as Excel, near the end of a trip: the trip as a spreadsheet by When and bag, with how many and what is packed; the header row stays in place."],
                fixed: ["A trip from the web app with laundry on now counts its per-night things the same way here."]),
        Release(version: "0.34", date: "27 Sep 2026", title: "Templates, said one way",
                changed: ["The app says Templates for the building blocks your trips are made from: the tab, Your templates, A new template, Delete template, On these templates, Pick at least one template. \u{201C}List\u{201D} now means only the list you pack from, and grab lists.",
                          "Settings \u{2192} Your lists is now Your choices: storage places, owners, packers, conditions and the When steps.",
                          "Trip settings: Save changes stays in sight at the bottom, above the keyboard."],
                fixed: ["Make the template was greyed out until a name was typed. It is always ready now, and says under it what is missing."]),
        Release(version: "0.33", date: "27 Sep 2026", title: "Again, from this trip",
                new: ["Trip settings → Start a new trip from this one: the same list as it ended up, with your own additions — nothing ticked, no dates, no review. The trip screen switches to the new trip and says so."]),
        Release(version: "0.32", date: "27 Sep 2026", title: "Trip settings",
                new: ["The gear beside a trip's count opens its settings: name, dates, Quick, lists, transport, season and food — the same choices as Create new trip.",
                      "Save rebuilds the list: what you ticked or added yourself stays, new things arrive, things no longer asked for go. The trip says how many."]),
        Release(version: "0.31", date: "27 Sep 2026", title: "The loop",
                new: ["How it works starts with the loop: Plan → Pack → Review → Refine, and round again. Violet is about your lists, green about one trip.",
                      "A trip, its review and Refine each show where they stand in the loop. Tap it for the whole picture, with \u{201C}You are here\u{201D}."]),
        Release(version: "0.30", date: "27 Sep 2026", title: "Refine",
                new: ["Your lists → Refine: what your trip reviews say a list carries for nothing — packed and never used, or listed and never packed, over at least two trips. Keep settles it for good; Drop takes it off that one list (it asks first) and the thing stays yours."]),
        Release(version: "0.29", date: "27 Sep 2026", title: "Bags, said one way",
                new: ["Deleting a bag offers No bag, and a bag nothing is packed in is deleted without choosing.",
                      "A bag that is also on your lists (like a day pack you pack on Travel) asks: keep it on those lists, or delete it completely.",
                      "A thing's details have Delete thing — it asks first; trips you already packed keep it."],
                changed: ["The app says Bags everywhere, in every screen and in this guide.",
                          "The thing editor's headings are bands in their own colour.",
                          "Deleting a bag says plainly that its things will be packed in another bag instead."]),
        Release(version: "0.28", date: "27 Sep 2026", title: "Headings in colour",
                changed: ["The thing editor's headings are in the colour of their buttons — Care orange, and purple for \u{201C}On these lists\u{201D} — instead of grey."]),
        Release(version: "0.27", date: "27 Sep 2026", title: "Larger headings",
                changed: ["The thing editor's headings (Name, Kept at home, Kind of thing, Usually packed in, When…) are larger."]),
        Release(version: "0.26", date: "26 Sep 2026", title: "Your bags have their own page",
                new: ["Care → Bags: tap a bag's name to open its page — rename it, set its numbers, see the things usually in it and the trips it went on, open its details, or delete it.",
                      "Renaming a bag carries the new name to your things, your lists and every trip.",
                      "Deleting a bag first asks which bag its things should move to.",
                      "Things have Brand, Colour and Notes."],
                changed: ["Create trip is always blue and ready. If a name or a list is missing, it says so under the button.",
                          "Delete trip, Delete list and Delete bag are small buttons at the side."]),
        Release(version: "0.25", date: "26 Sep 2026", title: "Set a place while packing",
                new: ["Sorted From where, each thing under \u{201C}No place set\u{201D} has Set place: tap it, tap one of your places (or type a new one), and the thing is kept there from now on.",
                      "Bags on a trip: an ⓘ explains the colours, and a bag without a maximum says \u{201C}no max\u{201D}."],
                changed: ["Your own \u{201C}When\u{201D} colours are made darker or lighter where needed, so every heading can be read, also on the green \u{201C}all packed\u{201D} screen."],
                fixed: ["Your bags: a number typed and left without Return was lost. Every number is now saved as you type.",
                        "A row that moved to another section could keep showing its old state."]),
        Release(version: "0.24", date: "26 Sep 2026", title: "Delete a trip",
                new: ["At the very end of a trip's list: Delete this trip. It asks first; your things and lists stay."]),
        Release(version: "0.23", date: "26 Sep 2026", title: "The app explains itself",
                new: ["Settings → What's new: every version, with what was added, changed, fixed and removed.",
                      "Settings → How it works: the whole app in plain words, screen by screen.",
                      "On a trip, the arrow before a section's name folds it away; tap again to open. Remembered per trip and per Sorting."],
                changed: ["The thing editor's buttons are a little smaller, so the headings stand out.",
                          "Arrived together with everything from 0.21 and 0.22, which the Mac tests had held back."]),
        Release(version: "0.22", date: "26 Sep 2026", title: "Two bugs from your screenshots",
                fixed: ["Whose it is showed your name once for every thing you own. Each person now appears once.",
                        "A row on a trip could keep showing \u{201C}not ticked\u{201D} while the trip had it ticked. Rows now redraw whenever their tick changes."]),
        Release(version: "0.21", date: "26 Sep 2026", title: "Dates like Booking, Today, bag headings",
                new: ["Create new trip: one date field and a month grid. Tap the first day, then the last. Two months side by side on the Mac.",
                      "Care calendar: Today, back to this month with today picked."],
                changed: ["Your bags: MAX KG · LITRES · EMPTY G stay at the top while the bags scroll."],
                removed: ["The two separate From and To date wheels."]),
        Release(version: "0.20", date: "26 Sep 2026", title: "Into and From where",
                new: ["From where: a trip sorted by where each thing is kept at home, so you can empty one cupboard at a time."],
                changed: ["Where is now called Into: the bag a thing goes into.",
                          "On a narrow screen the sorting buttons get a little slimmer so all four fit on one line."]),
        Release(version: "0.19", date: "25 Sep 2026", title: "Sorting",
                changed: ["On a trip, \u{201C}Sorting\u{201D} stands to the left of its buttons, on the same line."]),
        Release(version: "0.18", date: "25 Sep 2026", title: "The maintenance calendar",
                new: ["Care: List or Calendar. Each service sits on the day it falls due, coloured red, orange or green; tap a day to see what is due, with Done today.",
                      "\u{201C}N overdue · show in List\u{201D} above the grid."]),
        Release(version: "0.17", date: "25 Sep 2026", title: "Your bags",
                new: ["Care → Bags: your bags, each with its max weight, litres and empty weight.",
                      "A Bags card on every trip: how full each bag is, red when over."],
                fixed: ["Choosing a list in Search opens it."],
                removed: ["The bags shelf on Your lists (it lives in Care now)."]),
        Release(version: "0.16", date: "25 Sep 2026", title: "Search, list edits, your year",
                new: ["Search: the magnifier on Home, Trips, Your lists, Care and Actions finds things, lists, trips and to-dos.",
                      "Rename a list where its name is written; delete one (it asks first; your things stay).",
                      "Trips: Your year, month by month."],
                changed: ["Grab Lists, bigger suns, \u{201C}Create new trip\u{201D}, Dates and Quick on one line, short food words, group codes (GA, WET).",
                          "This Device down the side, Trips first. The tab is called Trips.",
                          "Reviewed trips fold away; thicker progress lines.",
                          "Greyed-out buttons can be read in daylight."],
                removed: ["The hint line under Create Event."]),
        Release(version: "0.15", date: "25 Sep 2026", title: "A list of your own",
                new: ["Your lists → + New: name a list and choose its shelf."]),
        Release(version: "0.14", date: "24 Sep 2026", title: "How many and Section, per list",
                changed: ["How many and Section belong to each list, as in the web app, not to the thing."]),
        Release(version: "0.13", date: "24 Sep 2026", title: "Colour is the message",
                changed: ["A ticked box is filled with colour."],
                removed: ["The mark inside a ticked box."]),
        Release(version: "0.12", date: "24 Sep 2026", title: "Change all",
                new: ["All your things: tick several, Change all, one answer for all of them, and Undo puts them back."]),
        Release(version: "0.11", date: "24 Sep 2026", title: "A real spreadsheet",
                new: ["All your things is a spreadsheet: sort, filter chips, choose and order the columns."]),
        Release(version: "0.10", date: "23 Sep 2026", title: "The table reads",
                changed: ["Places shown in full; cards quiet but visible."]),
        Release(version: "0.9", date: "23 Sep 2026", title: "The web app's look",
                new: ["Coloured headings, lists two across, and the table of all your things."]),
        Release(version: "0.8", date: "23 Sep 2026", title: "What your kit adds up to",
                new: ["Care: how many things, the total weight, the heavy end, and where it all lives."]),
        Release(version: "0.7", date: "23 Sep 2026", title: "More grab lists",
                new: ["Grab lists: things you take only sometimes.", "More than six grab lists; Home holds your six."]),
        Release(version: "0.6", date: "23 Sep 2026", title: "Where a trip stands",
                new: ["A trip says when everything is packed.", "Trips: Planned, Packing or Ready on every trip.",
                      "Your lists show how they are used."]),
        Release(version: "0.5", date: "23 Sep 2026", title: "Worth a look",
                new: ["Settings says when something in the library looks wrong."]),
        Release(version: "0.4", date: "23 Sep 2026", title: "Weather",
                new: ["A trip's weather for its place, and only the rain or cold gear you have not packed, each with a +."]),
        Release(version: "0.3", date: "23 Sep 2026", title: "Your lists, restore, the buy list",
                new: ["Settings → Your lists: storage places, owners, packers, conditions and \u{201C}When\u{201D} steps.",
                      "Restore from a backup file; a copy of what was here is kept first, and you can go back to it.",
                      "Actions has two sides: To do and To buy, with things worth buying suggested."]),
        Release(version: "0.2", date: "22 Sep 2026", title: "The app does the job",
                new: ["Your library on iPhone and Mac, kept in step through iCloud.",
                      "Home builds a trip; six grab lists.", "Packing: tap to tick, ⊘ not this time, When / Where / Category.",
                      "Things typed while packing join the trip.", "Care, Your things, the trip review, To do.",
                      "Edit a list and a thing; lists read in their sections.", "A backup with a real Save window."]),
        Release(version: "0.1", date: "21 Sep 2026", title: "The app exists",
                new: ["One app for the iPhone and the Mac."]),
    ]
}
