import Foundation

/// Every version, newest first, in his words — what was added, changed, fixed and
/// removed. His standing rule from the web apps: the version log and "How it works"
/// are updated on EVERY release. The UI test `testWhatsNewStartsWithThisVersion`
/// fails the build when the top entry is not the version being built, so a release
/// cannot slip out without its line here.
struct Release: Identifiable {
    let version: String
    let date: String
    let title: String
    var new: [String] = []
    var changed: [String] = []
    var fixed: [String] = []
    var removed: [String] = []
    var id: String { version }
}

enum Releases {
    static let all: [Release] = [
        Release(version: "0.68", date: "7 Oct 2026", title: "Beyond the list",
                new: ["On the Mac you can fill in a thing without the mouse: Tab goes from field to field, type to pick from a list, Return saves. \u{2318}N saves and starts the next thing with the same choices, \u{2318}\u{2193} and \u{2318}\u{2191} go through your things, \u{2318}J jumps to a field \u{2014} the new Thing menu lists them all.",
                      "Each storage place has its own small square code. Print its label on the P-touch (12 mm tape), stick it on the shelf, and point the iPhone's Camera at it: while you pack, the trip opens with only what to take from there; back from a trip, what goes back there; otherwise, everything kept there.",
                      "Your bags have pockets. Name them once on the bag's page; when you tick a thing, tap the pocket it went into. Ask Siri \u{201C}Where is my charger?\u{201D} or search for it: \u{201C}Backpack, front pocket.\u{201D}",
                      "Set \u{201C}I leave at\u{201D} on a trip: 15 minutes before you go, your iPhone names what is still unticked \u{2014} and on the last day, what is not in a bag yet.",
                      "Kits: a pouch that stays packed can hold your things. On a trip it is one line, \u{201C}Camp pouch \u{00B7} 3 inside\u{201D}; take one thing out and the trip says \u{201C}1 missing\u{201D}. It weighs itself plus what is inside.",
                      "After a trip, the review starts with what Apple Health saw you do. Use these marks the gear of workouts you skipped as didn't use. Tell the app who you are in Your choices \u{2192} Owners (This is me).",
                      "A reviewed trip can go into your Obsidian vault as one page \u{2014} weather, workouts, bags, photos, what you didn't use, missed and bought, your notes. The Mac writes it; your own edits on the page stay.",
                      "Each template has its own reminders, each with a When. A trip gets them as To do lines; when one is due it shows under Check before you go and on Home.",
                      "Pack by voice (a test, iPhone): it reads what is still to pack, place by place; answer packed, skip, later, where or stop. It asks once more for what you left for later, and a place's code starts it right there."],
                changed: ["A thing's Section list can rename a section, move it up or down, or remove it (it asks first). Nothing changes until Save.",
                          "Search also finds words in your things' notes and in the notes your templates keep for them.",
                          "Press Weather while still typing the place: it no longer freezes on Looking\u{2026}"]),
        Release(version: "0.67", date: "7 Oct 2026", title: "Your field test: lines without air, an open calendar",
                new: ["Create new trip: the calendar is always open \u{2014} tap the first day, then the last; Create waits for the last day and says so. Clear dates beside the range leaves the trip without dates. In Trip settings, tap the dates to change them.",
                      "Each workout has its own Indoor / Outdoor / Race: Run outdoors and Swim indoors on the same trip \u{2014} on Create new trip and in Trip settings."],
                changed: ["Full trip or Quick is a choice right under the trip's name, with a line saying what Quick leaves out. The Dates switch is gone.",
                          "Lines without air: a trip's packing list, a template's things, To do, To buy and a grab list show each line as tall as its words \u{2014} far more on one screen.",
                          "Settings: What's new, How it works, Your first real trip and Open a shared link sit together in one card, and the cards are closer. The grab buttons on Home are one slim line each.",
                          "Every screen's top line is tidied: the title and the buttons beside it sit on one line, and the empty strip at the top is gone. On Home, Grab and go is the first line.",
                          "On the Mac the window has no title bar any more: each tab's title and buttons sit up beside the three window buttons, so the screen starts higher. Drag that top strip to move the window.",
                          "Share's arrow sits in the middle of its button. While arranging a template, a heading's \u{2261} is purple on a soft purple patch and a thing's \u{2261} light grey, so they are easy to tell apart."]),
        Release(version: "0.66", date: "6 Oct 2026", title: "Column widths",
                new: ["All your things \u{00B7} table: make a column wider or narrower \u{2014} drag the short line at the right edge of its heading, the Thing column too. Each keeps its width; a double tap on the line puts back its own."]),
        Release(version: "0.65", date: "6 Oct 2026", title: "A table without air",
                changed: ["All your things \u{00B7} table: no air between the lines \u{2014} each row is as tall as its words, with smaller tick boxes; the open arrow sits on the name's line, and a short table starts at the top of its window."]),
        Release(version: "0.64", date: "6 Oct 2026", title: "Drop-downs, your own bags, and sections",
                new: ["Every choose-one list on a thing's page and on a template's row is now a drop-down: tap it, tap your choice. Kept at home is chosen from your places; a new place made there joins Your choices.",
                      "Trips can be sorted by Section: Sorting is one drop-down with When, Into, From where, Category and Section.",
                      "A thing's page sets its section on each template it is on \u{2014} or makes a new one \u{2014} without opening the template. Trips still ahead follow."],
                changed: ["Usually packed in offers only your own bags from Your bags, plus No bag \u{2014} no built-in names you don't have, and a renamed bag shows its new name.",
                          "A thing's page reads in a new order: Name, Notes, Kind of thing, Whose it is, On these templates, Kept at home, Usually packed in, When, then Weight, Brand, Colour, Condition, Care, and last On a plane and Valid until.",
                          "Liquid and Not allowed in the cabin without their explanations."]),
        Release(version: "0.63", date: "5 Oct 2026", title: "Arrange a template",
                new: ["Arrange your templates: on a template, tap Arrange, then hold \u{2261} and drag a heading (its things come along) or a thing to where it belongs \u{2014} even under another heading. Tap a heading's name to rename it or remove it; its things stay. New trips pack in the new order."]),
        Release(version: "0.62", date: "5 Oct 2026", title: "The big check-up: everything we found, put right",
                new: ["Your choices: the pen beside each entry renames it \u{2014} everything that said the old name follows \u{2014} and the arrows move it up or down (owners stay A to Z).",
                      "A thing's page: a Care schedule with what to do, your places a tap away under Kept at home, and \u{201C}No bag\u{201D} under Usually packed in.",
                      "A thing's page shows, under Notes, what your templates say about it \u{2014} \u{201C}On the Swim template: \u{2026}\u{201D}.",
                      "A template's page can move it to another activity area.",
                      "Trip settings: Pack weather gear anyway \u{2014} Rain, Cold, Heat, Wind or Snow.",
                      "Settings says when you last saved a backup on this device, and where your library came from.",
                      "To do and To buy: a line taken off with \u{2715} can be brought back with Undo."],
                changed: ["A new look: Apple's standard text sizes and slim buttons throughout \u{2014} calmer and more compact, with more on every screen. A trip's rows, tick circles and the grab-list buttons are smaller, Your things and Search show a thing's name and details on one line, and on the Mac everything is Mac-sized.",
                          "A thing's note stays the thing's: on a template it shows on every row and follows the thing when you change it.",
                          "Changes saved on a template's row \u{2014} bag, When, how many, note, \u{201C}Only on\u{201D} \u{2014} reach your trips still ahead, as changes to the thing do.",
                          "Choose from your things: what you tick arrives in the order you ticked it.",
                          "A name you already have is never added twice \u{2014} on a template, in Your things, in Grab Lists and in Your choices it says so instead.",
                          "A shared template with a name you already have asks for a name of its own. Replace keeps your template's look, sections and bags, and says first what comes in and what leaves.",
                          "Template cards say \u{201C}Next: in 30 days\u{201D} for a trip still to come.",
                          "Sharing a trip sends just the list: your \u{201C}not this time\u{201D} marks, notes and scale readings stay with you. A trip someone sends you keeps its whole list when you change its settings.",
                          "A new trip started from an old one begins clean, and setting something aside takes its tick away \u{2014} so the review and Your year count only what really went.",
                          "Every bag on a trip shows on Bags, even before anything is weighed: tap it to weigh.",
                          "Templates without an activity area can go on a trip, under Other templates. Weather suggestions skip things not in use.",
                          "The calendar keeps one height, and tapping the date box waits for the last day. Trip dates read \u{201C}3 Oct 2026\u{201D} everywhere.",
                          "A swipe no longer loses an unsaved review or unsaved trip settings. On the Mac, Escape closes a trip's windows.",
                          "All your things offers your own bags and every owner. The table has no Bags column any more \u{2014} bags live in Your bags.",
                          "Change all says what it changed and refuses a weight that is not a number; Undo puts back only what Change all changed.",
                          "A condition chosen in the table, like Needs replacing, counts everywhere \u{2014} To buy offers it. Things set that way earlier are put right by themselves.",
                          "Care also lists things that are on no template, leaves out things not in use, and the year ahead counts real months.",
                          "To buy and Reminders stay in step: removing or unticking a line does the same in Reminders, and a line deleted there can be sent again.",
                          "Grab lists: saving keeps today's ticks, Start over sets the sometimes-things aside again, and a waiting list in Grab Lists opens with a tap.",
                          "Your choices: why something cannot be removed appears right under it, and says what still uses it.",
                          "The iCloud card says \u{201C}Can't tell\u{201D} when it cannot check, instead of a green \u{201C}Working\u{201D}.",
                          "The notes for each new version now show in TestFlight as What to Test.",
                          "On the Mac, Escape closes every window the way its Cancel or Done does, and never saves by accident; on an iPhone with a keyboard, Command-period does the same.",
                          "Your choices: Owners shows the owners your things already belong to, even if you never added one yourself.",
                          "Remind me to pack: when this device does not allow reminders, Settings says so every time, whether the switch is on or off.",
                          "Closing the restore window by swiping it away says \u{201C}Nothing was replaced.\u{201D}, as Cancel does."],
                fixed: ["On a new, empty device, Sync no longer hides the welcome doors. Cancel after looking inside a backup changes nothing; safety copies show your own clock time; the Restore window fits the iPhone.",
                        "Bringing back an older backup puts each thing's own note and amount back, and pictures saved slightly irregularly come back too.",
                        "A grab list deleted on your other device closes instead of turning into another one. A Shortcut, the Action button or a reminder opens its list even when another window is open.",
                        "A to-do found in Search opens the To do tab; Home's Templates number matches Your templates.",
                        "Remind me to pack says so when the iPhone does not allow reminders, and names every reminder day.",
                        "To do and To buy each keep their own half-typed line. Weights take decimals, like 12,5.",
                        "Your bags shows a number changed on a bag's page straight away, and a bag's Delete says what to choose first.",
                        "Buying something on site puts the trip at On site in the loop too; the way home shows photos of things in no bag.",
                        "\u{201C}No template\u{201D} works in the review; Set place and the review's Add say what is missing.",
                        "Deleting a template also removes its filter and its column in the table, and the table sorts å, ä and ö like everywhere else.",
                        "\u{201C}Strength training\u{201D} no longer gets a train picture, and covers never show an emoji.",
                        "Two very long names that began the same could overwrite each other."]),
        Release(version: "0.61", date: "5 Oct 2026", title: "Your own grab lists, and a restore that brings back everything",
                new: ["A grab list you made yourself can be deleted: Edit, then Delete grab list at the bottom. It asks first."],
                changed: ["Grab lists you make yourself can now be filled: Edit, add things, mark one \u{201C}1 in 10\u{201D}, Save \u{2014} it all stays.",
                          "Ticks on your own grab lists stay when you close the list and open it again.",
                          "Off Home now really takes a grab list off Home: it waits in Grab Lists until you put it back, and Home shows one tile fewer.",
                          "After Make, Grab Lists says where the new list went \u{2014} on Home, or waiting because Home is full.",
                          "Restore from a file no longer refuses a backup once a bag is marked for the cabin, and the copy kept before a restore works too. A backup now brings back exactly what was there: every thing keeps its own note, and a thing whose only template was deleted is no longer left out."]),
        Release(version: "0.60", date: "4 Oct 2026", title: "Find a thing on a template",
                new: ["An open template has a search field above its list: type part of a name and only the matching things show, with how many of all. The \u{2715} brings them all back."],
                changed: ["Worth a look offers to remove a photo only when it can tell the photo is more than a day old."]),
        Release(version: "0.59", date: "4 Oct 2026", title: "A deleted trip takes its photos along",
                new: ["Settings \u{2192} Worth a look: a photo left behind by a trip deleted earlier is pointed out, with Remove it to take it away. Only photos older than a day, so one still on its way from your other device is never touched."],
                changed: ["Deleting a trip now removes its bag photos too \u{2014} unless something else, like a thing, still shows the same photo.",
                          "Whose it is: \u{201C}Nobody's in particular\u{201D} is now \u{201C}Both have one\u{201D} \u{2014} on a thing, and in the table's Owner filter.",
                          "A thing's page: Notes sit right under its name."]),
        Release(version: "0.58", date: "4 Oct 2026", title: "The table: filter by anything, sort by levels",
                new: ["All your things \u{00B7} table: Filter by any column \u{2014} Owner, Packed by, Storage, each template and its sections, and every other column. Tick the answers your things have; the number says how many. A pill above the table shows each filter, and its \u{2715} takes it off.",
                      "Sort by up to three levels: Sort by, then by, then by. A template can sort by its sections in its own order \u{2014} Travel, then Travel \u{00B7} section.",
                      "The arrow beside a thing's name in the table opens the thing; Save or Cancel brings you back to the same spot.",
                      "On the Mac, the table is a window of its own: drag it as wide as you like to see more columns, or make it full screen."],
                changed: ["Choosing columns: the up and down arrows, and Hide, are each a fingertip wide \u{2014} much easier to hit.",
                          "In the table, a blank always sorts last, whichever way round."]),
        Release(version: "0.57", date: "3 Oct 2026", title: "On site, and one bar per bag",
                new: ["On site, the step after Pack. Once a trip has begun (or something was bought on site), its On site page holds what you bought, what you left on site, maintenance notes, and Pack to go home.",
                      "A maintenance note (\u{201C}zip broken\u{201D}), written on site or on the way home, also goes onto the thing itself, dated \u{2014} Care has it after the trip."],
                changed: ["The loop has five steps: Plan \u{203A} Pack \u{203A} On site \u{203A} Review \u{203A} Refine \u{2014} in the line under a trip's name and in the picture. Pack to go home opens from the On site page.",
                          "Each bag on a trip has one thick bar: the grey is what the bag may carry, the blue what is in it \u{2014} orange close to its max, red over.",
                          "Headings lead: on a thing, a template's row, Create new trip, Trip settings, Your choices and the review, each heading is clearly the biggest thing in its part; the buttons under it are smaller.",
                          "Add, New, Make and Weather are never grey: press one before typing and it says under the field what is missing.",
                          "What goes from To buy to Reminders carries the day you sent it.",
                          "A thing's Notes show every line, one under the other."]),
        Release(version: "0.56", date: "3 Oct 2026", title: "Your field test, part two",
                new: ["Pack to go home: search the list; Tick everything (and Clear the ticks); the heading counts what was used up \u{2014} \u{201C}1/2 \u{00B7} 1 used up\u{201D}. Each line takes a note (\u{201C}zip broken\u{201D}), and Open changes the thing and comes straight back.",
                      "Up to three photos of each packed bag. Tap one to see it large; Next steps through them. The way home shows them all.",
                      "Valid until says how far away the date is \u{2014} \u{201C}in 10 days\u{201D}, \u{201C}in 4 months\u{201D}, red once it has run out \u{2014} and +1 month, +6 months, +1 year, +5 years or +10 years sets it in one tap.",
                      "Choose from your things: every group folds with its arrow, or all at once with Fold all. A folded group still says how many things it holds and how many you ticked.",
                      "An \u{2715} in every search field empties it in one tap.",
                      "Settings: Your first real trip in 6 steps has its own door.",
                      "Save as Excel has a Category column, right after Thing."],
                changed: ["\u{201C}Shelf\u{201D} is now \u{201C}Activity area\u{201D}, the group a template lives in (GA, WET\u{2026}). Grab lists that are not on Home wait in Grab Lists.",
                          "\u{201C}Bought there\u{201D} is now \u{201C}Bought on site\u{201D}.",
                          "Picking trip dates: after the last day the calendar stays open and shows the range \u{2014} \u{201C}6 Oct \u{2013} 16 Oct \u{00B7} 10 nights\u{201D}. OK keeps it; Cancel puts the dates back.",
                          "Used up is taken back with Undo.",
                          "Your things: what you just added stays at the top, under Just added, until you leave the screen.",
                          "Renaming a bag takes each trip's scale reading and bag photos along; deleting one moves its photos to the bag its things go to."]),
        Release(version: "0.55", date: "3 Oct 2026", title: "Fixes from your field test",
                new: ["The Action button: a new Shortcuts action, Choose a grab list. One press opens all your grab lists as big tiles; tap the one for today.",
                      "On a trip, tap a bag: Goes in the cabin can be switched on right there \u{2014} also for a bag that was only a name on your lines. It then shows in Care \u{2192} Bags too."],
                changed: ["Quick says that Transport still counts: pick Plane and the cabin is checked.",
                          "A row on a template says what it is limited to: Only on: Summer.",
                          "What you tick in Reminders in the shop is ticked here as soon as you come back to the app."]),
        Release(version: "0.54", date: "3 Oct 2026", title: "iCloud sync, made visible",
                new: ["Settings \u{2192} iCloud sync: when this device last sent and received, what iCloud does not have yet, and \u{2014} if a send failed \u{2014} why, in plain words.",
                      "Sync now: this device checks in, and the other device's Settings shows it within a minute or so. A direct test of each direction.",
                      "Copy details for Claude: everything iCloud recorded on this device, to paste into the chat."]),
        Release(version: "0.53", date: "2 Oct 2026", title: "Pack to go home",
                new: ["Once a trip has begun (or something was bought there), the trip shows Pack to go home: what went and what you bought there, bag by bag, with ticks of its own. Used up takes a thing off. The photos of your packed bags sit at the top, to repack from. The ticks of the way out stay as they were, for the review."]),
        Release(version: "0.52", date: "2 Oct 2026", title: "A photo of the packed bag, and Bought there",
                new: ["Tap a bag on a trip's Bags: besides the luggage scale, Take a photo (or Choose a photo) of it packed. It stays with the trip; tap it to see it large \u{2014} the picture to repack from on the way home.",
                      "Bought something on the trip? Type it at the bottom of the list and press Bought there: it goes on, ticked, marked Bought there."]),
        Release(version: "0.51", date: "2 Oct 2026", title: "Shortcuts and the Action button",
                new: ["Two Shortcuts actions: Open a grab list (pick Swim, Bike, Run\u{2026}) and Open my next trip. Put one on the iPhone's Action button (Settings \u{2192} Action Button \u{2192} Shortcut), on the Home Screen, or ask Siri; they work in Shortcuts on the Mac too."]),
        Release(version: "0.50", date: "2 Oct 2026", title: "The luggage scale, and To buy in Reminders",
                new: ["On a trip's Bags, tap a bag and type what the luggage scale says. From then on that is the bag's weight \u{2014} the bag itself and everything never weighed included \u{2014} and the things' own sum stays under it. Over its max, the card turns red. Clear takes the reading away.",
                      "To do \u{2192} To buy: Send to Reminders puts the open lines into a Reminders list of their own, \u{201C}To buy \u{00B7} Packing\u{201D}, to take to the shop. Each line goes once; what you tick there is ticked here the next time you open the list."]),
        Release(version: "0.49", date: "2 Oct 2026", title: "Counting down, and reminders",
                new: ["Home counts down to your next trip, under the grab lists: the days in big figures, the trip, and the next packing step with when it is due. Tap it to open the trip.",
                      "Settings \u{2192} Remind me to pack: on this device, at 9 in the morning of the day each packing step is due (a week ahead, the day before, the morning\u{2026}), the trip and what is left to pack. Tap a reminder to open the trip. Off until you turn it on, so each device reminds you only if you want it to."]),
        Release(version: "0.48", date: "2 Oct 2026", title: "Check before you go",
                new: ["A trip shows Check before you go at the top when something needs you. On a plane trip: what in a cabin bag the airport stops \u{2014} not allowed on board in red, a liquid in orange (100 ml at most, in the clear bag). And what runs out before you are home; a passport or ID card six months ahead. Tap a line to open the thing and put it right.",
                      "A thing's page has On a plane (Liquid, Not allowed in the cabin) and Valid until (Add a date).",
                      "A bag's page has Goes in the cabin. A carry-on, hand luggage or cabin bag starts switched on."]),
        Release(version: "0.47", date: "2 Oct 2026", title: "Your first real trip",
                new: ["How it works starts with Your first real trip in 6 steps: backup, tidy your things, templates, the trip, packing, and the review afterwards."],
                changed: ["Laundry: you choose how many nights you pack for before a wash (3, 4, 5, 7, 10 or 14) — on Create new trip and in Trip settings. Every count, bag weight and the Excel file follow."]),
        Release(version: "0.46", date: "2 Oct 2026", title: "Icons, and eight grab lists",
                new: ["Every template has an icon — 50 drawn ones to choose from. Each starts with the one its name suggests (Swim, Bike, Run, Car, Plane…); tap the square on a template to pick another, or Letter for its first letter."],
                changed: ["Home holds eight grab lists, four in a row and slimmer. Free places fill from your shelf; when Home is full, a new list waits there as before.",
                          "Settings: Save a backup and Restore are further down, under Your choices, What's new and How it works.",
                          "Your choices: each part says what it is and where you use it.",
                          "A shared grab list takes a free place on Home, and says where it went."]),
        Release(version: "0.45", date: "1 Oct 2026", title: "A change to a thing reaches your trips",
                changed: ["Change a thing — its bag, weight, place or name — and the trips still ahead follow: coming-up and current trips, on every line you have not ticked and not changed on the trip itself. Ticked lines and finished trips keep what they were packed with. A bag chosen for one template still wins there."]),
        Release(version: "0.44", date: "30 Sep 2026", title: "The iPhone hears about changes",
                fixed: ["The iPhone app was built without permission to be told when iCloud has something new, so a trip made on the Mac showed up only after the app was opened again (your A.4). It now carries it, like the Mac app."]),
        Release(version: "0.43", date: "30 Sep 2026", title: "Actions is now To do",
                changed: ["The Actions tab is called To do — your choice. It still has both sides: To do and To buy."]),
        Release(version: "0.42", date: "28 Sep 2026", title: "Choosing things for a template",
                new: ["A template: Choose from your things. Every thing you own, grouped by Kind, From where, Into, When or A–Z, with a search. Tick as many as you like and Add them in one go; what is already on the template says so. A name you own nothing by becomes a new thing, straight onto the template.",
                      "A template's own things can be grouped the same ways: its sections, When, Into, From where, Kind or A–Z.",
                      "Trips: All your trips under Your year — trips, nights away, places and things packed, ever — and under it the map of where they went. Tap the map for the whole map."]),
        Release(version: "0.41", date: "28 Sep 2026", title: "Your test comments, part 2",
                new: ["How it works has a Words chapter: every word the app uses, said once — template, shelf, list, kit, the loop, review, refine and more."],
                changed: ["The loop strip carries the mark of the tab where each step is done: Plan on Home, Pack and Review on Trips, Refine on Templates. The picture says so too.",
                          "Refine on the Templates tab stands out: steps going up, in violet, with how many things wait.",
                          "Review: type what you missed, pick the template it goes onto, then Add it to that template — in that order, and the button says where."]),
        Release(version: "0.40", date: "28 Sep 2026", title: "Your test comments, part 1",
                new: ["Trip settings has the trip's place. Change it there and the weather starts again from the new place.",
                      "The date grid has Cancel: it closes and puts the dates back.",
                      "Taking a thing off a template with ✕ asks first, in the middle of the screen. The thing stays in Your things.",
                      "Save as Excel has two more columns: From where (where it is kept at home) and Into (the bag)."],
                changed: ["A pen, not a gear, opens a trip's settings.",
                          "Share is a real button, beside Save as Excel. Done, Save, Cancel and Share look like buttons everywhere.",
                          "The workouts have their own colours: Swim blue, Bike yellow, Run green, Strength orange, Breath work lavender, Mobility pink. Context sits set in under them, in grey.",
                          "Quick says what it means in green while it is on.",
                          "Grab lists: the count stays at the top while you scroll, and Not yet is a red card in the middle of the screen.",
                          "Headings on Care, Templates and Your choices are larger and in capitals. The heavy end is now Heaviest things.",
                          "In a thing's editor, each field sits right under its heading.",
                          "Trips: Now, Coming up and Done (was Been). Now is always there, with how many. The Reviewed arrow is much larger.",
                          "A new template asks: On which shelf should it live?"],
                fixed: ["A trip with a place but no forecast (already over, or too far ahead) now reaches the map. Before, only trips whose weather came back were on it."],
                removed: ["The round arrow at the end of the loop strip — it looked like a reload button."]),
        Release(version: "0.39", date: "28 Sep 2026", title: "A crash fixed",
                fixed: ["Changing a trip's dates, templates or laundry in Trip settings could close the app when the same thing was on the trip twice (from two templates, in two bags). Now each of those lines comes back once, with its own tick."]),
        Release(version: "0.38", date: "27 Sep 2026", title: "Share",
                new: ["Share a trip (at the end of its list), a template or a grab list (at their top): a link that opens in the web app and in this one, a QR code when it is short enough, and a trip also as a file.",
                      "Settings \u{2192} Open a shared link: paste a link or code and see what it holds. A trip arrives as a new trip, unticked. A template arrives as a new one, or in place of yours with the same name; things you already have keep your details. A grab list waits on your shelf."]),
        Release(version: "0.37", date: "27 Sep 2026", title: "Where you have been",
                new: ["Trips → the pin at the top: a map of your trips. One pin per place, with a number when you went more than once, a line through the trips oldest first, and a card per place with its trips. Tap a pin to find its card.",
                      "Trips that name a place but never looked up their weather can be found on the map in one press."],
                changed: ["Looking up a trip's weather now keeps the place's name for the map too."]),
        Release(version: "0.36", date: "27 Sep 2026", title: "Everything at once",
                new: ["Near the end of a trip: Tick everything (it says how many are still unticked), and Clear every tick, which asks first. Lines set aside stay out of both.",
                      "The weather card: Add all, when it asks for two or more things."],
                fixed: ["Weather gear you add from your own templates remembers where it came from, so the review counts it for that thing, and its weight reaches the bags."]),
        Release(version: "0.35", date: "27 Sep 2026", title: "Laundry and Excel",
                new: ["Laundry, on Create new trip and in Trip settings: wash and wear again, so per-night things count 4 nights at most. The line says \u{00D7}4 with a washtub.",
                      "Save as Excel, near the end of a trip: the trip as a spreadsheet by When and bag, with how many and what is packed; the header row stays in place."],
                fixed: ["A trip from the web app with laundry on now counts its per-night things the same way here."]),
        Release(version: "0.34", date: "27 Sep 2026", title: "Templates, said one way",
                changed: ["The app says Templates for the building blocks your trips are made from: the tab, Your templates, A new template, Delete template, On these templates, Pick at least one template. \u{201C}List\u{201D} now means only the list you pack from, and grab lists.",
                          "Settings \u{2192} Your lists is now Your choices: storage places, owners, packers, conditions and the When steps.",
                          "Trip settings: Save changes stays in sight at the bottom, above the keyboard."],
                fixed: ["Make the template was greyed out until a name was typed. It is always ready now, and says under it what is missing."]),
        Release(version: "0.33", date: "27 Sep 2026", title: "Again, from this trip",
                new: ["Trip settings → Start a new trip from this one: the same list as it ended up, with your own additions — nothing ticked, no dates, no review. The trip screen switches to the new trip and says so."]),
        Release(version: "0.32", date: "27 Sep 2026", title: "Trip settings",
                new: ["The gear beside a trip's count opens its settings: name, dates, Quick, lists, transport, season and food — the same choices as Create new trip.",
                      "Save rebuilds the list: what you ticked or added yourself stays, new things arrive, things no longer asked for go. The trip says how many."]),
        Release(version: "0.31", date: "27 Sep 2026", title: "The loop",
                new: ["How it works starts with the loop: Plan → Pack → Review → Refine, and round again. Violet is about your lists, green about one trip.",
                      "A trip, its review and Refine each show where they stand in the loop. Tap it for the whole picture, with \u{201C}You are here\u{201D}."]),
        Release(version: "0.30", date: "27 Sep 2026", title: "Refine",
                new: ["Your lists → Refine: what your trip reviews say a list carries for nothing — packed and never used, or listed and never packed, over at least two trips. Keep settles it for good; Drop takes it off that one list (it asks first) and the thing stays yours."]),
        Release(version: "0.29", date: "27 Sep 2026", title: "Bags, said one way",
                new: ["Deleting a bag offers No bag, and a bag nothing is packed in is deleted without choosing.",
                      "A bag that is also on your lists (like a day pack you pack on Travel) asks: keep it on those lists, or delete it completely.",
                      "A thing's details have Delete thing — it asks first; trips you already packed keep it."],
                changed: ["The app says Bags everywhere, in every screen and in this guide.",
                          "The thing editor's headings are bands in their own colour.",
                          "Deleting a bag says plainly that its things will be packed in another bag instead."]),
        Release(version: "0.28", date: "27 Sep 2026", title: "Headings in colour",
                changed: ["The thing editor's headings are in the colour of their buttons — Care orange, and purple for \u{201C}On these lists\u{201D} — instead of grey."]),
        Release(version: "0.27", date: "27 Sep 2026", title: "Larger headings",
                changed: ["The thing editor's headings (Name, Kept at home, Kind of thing, Usually packed in, When…) are larger."]),
        Release(version: "0.26", date: "26 Sep 2026", title: "Your bags have their own page",
                new: ["Care → Bags: tap a bag's name to open its page — rename it, set its numbers, see the things usually in it and the trips it went on, open its details, or delete it.",
                      "Renaming a bag carries the new name to your things, your lists and every trip.",
                      "Deleting a bag first asks which bag its things should move to.",
                      "Things have Brand, Colour and Notes."],
                changed: ["Create trip is always blue and ready. If a name or a list is missing, it says so under the button.",
                          "Delete trip, Delete list and Delete bag are small buttons at the side."]),
        Release(version: "0.25", date: "26 Sep 2026", title: "Set a place while packing",
                new: ["Sorted From where, each thing under \u{201C}No place set\u{201D} has Set place: tap it, tap one of your places (or type a new one), and the thing is kept there from now on.",
                      "Bags on a trip: an ⓘ explains the colours, and a bag without a maximum says \u{201C}no max\u{201D}."],
                changed: ["Your own \u{201C}When\u{201D} colours are made darker or lighter where needed, so every heading can be read, also on the green \u{201C}all packed\u{201D} screen."],
                fixed: ["Your bags: a number typed and left without Return was lost. Every number is now saved as you type.",
                        "A row that moved to another section could keep showing its old state."]),
        Release(version: "0.24", date: "26 Sep 2026", title: "Delete a trip",
                new: ["At the very end of a trip's list: Delete this trip. It asks first; your things and lists stay."]),
        Release(version: "0.23", date: "26 Sep 2026", title: "The app explains itself",
                new: ["Settings → What's new: every version, with what was added, changed, fixed and removed.",
                      "Settings → How it works: the whole app in plain words, screen by screen.",
                      "On a trip, the arrow before a section's name folds it away; tap again to open. Remembered per trip and per Sorting."],
                changed: ["The thing editor's buttons are a little smaller, so the headings stand out.",
                          "Arrived together with everything from 0.21 and 0.22, which the Mac tests had held back."]),
        Release(version: "0.22", date: "26 Sep 2026", title: "Two bugs from your screenshots",
                fixed: ["Whose it is showed your name once for every thing you own. Each person now appears once.",
                        "A row on a trip could keep showing \u{201C}not ticked\u{201D} while the trip had it ticked. Rows now redraw whenever their tick changes."]),
        Release(version: "0.21", date: "26 Sep 2026", title: "Dates like Booking, Today, bag headings",
                new: ["Create new trip: one date field and a month grid. Tap the first day, then the last. Two months side by side on the Mac.",
                      "Care calendar: Today, back to this month with today picked."],
                changed: ["Your bags: MAX KG · LITRES · EMPTY G stay at the top while the bags scroll."],
                removed: ["The two separate From and To date wheels."]),
        Release(version: "0.20", date: "26 Sep 2026", title: "Into and From where",
                new: ["From where: a trip sorted by where each thing is kept at home, so you can empty one cupboard at a time."],
                changed: ["Where is now called Into: the bag a thing goes into.",
                          "On a narrow screen the sorting buttons get a little slimmer so all four fit on one line."]),
        Release(version: "0.19", date: "25 Sep 2026", title: "Sorting",
                changed: ["On a trip, \u{201C}Sorting\u{201D} stands to the left of its buttons, on the same line."]),
        Release(version: "0.18", date: "25 Sep 2026", title: "The maintenance calendar",
                new: ["Care: List or Calendar. Each service sits on the day it falls due, coloured red, orange or green; tap a day to see what is due, with Done today.",
                      "\u{201C}N overdue · show in List\u{201D} above the grid."]),
        Release(version: "0.17", date: "25 Sep 2026", title: "Your bags",
                new: ["Care → Bags: your bags, each with its max weight, litres and empty weight.",
                      "A Bags card on every trip: how full each bag is, red when over."],
                fixed: ["Choosing a list in Search opens it."],
                removed: ["The bags shelf on Your lists (it lives in Care now)."]),
        Release(version: "0.16", date: "25 Sep 2026", title: "Search, list edits, your year",
                new: ["Search: the magnifier on Home, Trips, Your lists, Care and Actions finds things, lists, trips and to-dos.",
                      "Rename a list where its name is written; delete one (it asks first; your things stay).",
                      "Trips: Your year, month by month."],
                changed: ["Grab Lists, bigger suns, \u{201C}Create new trip\u{201D}, Dates and Quick on one line, short food words, group codes (GA, WET).",
                          "This Device down the side, Trips first. The tab is called Trips.",
                          "Reviewed trips fold away; thicker progress lines.",
                          "Greyed-out buttons can be read in daylight."],
                removed: ["The hint line under Create Event."]),
        Release(version: "0.15", date: "25 Sep 2026", title: "A list of your own",
                new: ["Your lists → + New: name a list and choose its shelf."]),
        Release(version: "0.14", date: "24 Sep 2026", title: "How many and Section, per list",
                changed: ["How many and Section belong to each list, as in the web app, not to the thing."]),
        Release(version: "0.13", date: "24 Sep 2026", title: "Colour is the message",
                changed: ["A ticked box is filled with colour."],
                removed: ["The mark inside a ticked box."]),
        Release(version: "0.12", date: "24 Sep 2026", title: "Change all",
                new: ["All your things: tick several, Change all, one answer for all of them, and Undo puts them back."]),
        Release(version: "0.11", date: "24 Sep 2026", title: "A real spreadsheet",
                new: ["All your things is a spreadsheet: sort, filter chips, choose and order the columns."]),
        Release(version: "0.10", date: "23 Sep 2026", title: "The table reads",
                changed: ["Places shown in full; cards quiet but visible."]),
        Release(version: "0.9", date: "23 Sep 2026", title: "The web app's look",
                new: ["Coloured headings, lists two across, and the table of all your things."]),
        Release(version: "0.8", date: "23 Sep 2026", title: "What your kit adds up to",
                new: ["Care: how many things, the total weight, the heavy end, and where it all lives."]),
        Release(version: "0.7", date: "23 Sep 2026", title: "More grab lists",
                new: ["Grab lists: things you take only sometimes.", "More than six grab lists; Home holds your six."]),
        Release(version: "0.6", date: "23 Sep 2026", title: "Where a trip stands",
                new: ["A trip says when everything is packed.", "Trips: Planned, Packing or Ready on every trip.",
                      "Your lists show how they are used."]),
        Release(version: "0.5", date: "23 Sep 2026", title: "Worth a look",
                new: ["Settings says when something in the library looks wrong."]),
        Release(version: "0.4", date: "23 Sep 2026", title: "Weather",
                new: ["A trip's weather for its place, and only the rain or cold gear you have not packed, each with a +."]),
        Release(version: "0.3", date: "23 Sep 2026", title: "Your lists, restore, the buy list",
                new: ["Settings → Your lists: storage places, owners, packers, conditions and \u{201C}When\u{201D} steps.",
                      "Restore from a backup file; a copy of what was here is kept first, and you can go back to it.",
                      "Actions has two sides: To do and To buy, with things worth buying suggested."]),
        Release(version: "0.2", date: "22 Sep 2026", title: "The app does the job",
                new: ["Your library on iPhone and Mac, kept in step through iCloud.",
                      "Home builds a trip; six grab lists.", "Packing: tap to tick, ⊘ not this time, When / Where / Category.",
                      "Things typed while packing join the trip.", "Care, Your things, the trip review, To do.",
                      "Edit a list and a thing; lists read in their sections.", "A backup with a real Save window."]),
        Release(version: "0.1", date: "21 Sep 2026", title: "The app exists",
                new: ["One app for the iPhone and the Mac."]),
    ]
}
